version: '3'
services:
  api-spopee:
    build: .
    depends_on:
        - mysql
    container_name: api-spopee
    environment:
      MYSQL: mysql
    ports:
        - "8080:8080"
    links:
        - mysql    

  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    