version: '3'
services:
  api-shopee:
    build: .
    depends_on:
        - mysql
    container_name: api-shopee
    environment:
		MYSQL: mysql
	links:
		- mysql
    ports:
        - "8080:8080"

  mysql:
    build: ./database
    container_name: mysql
    environment:
      	MYSQL_ALLOW_EMPTY_PASSWORD: "yes"



    